script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
install_dir="$script_dir/install"
export JAVA_HOME="$install_dir/java/jdk-17.0.12"
export JDK_HOME="$install_dir/java/jdk-17.0.12"
export JRE_HOME="$install_dir/java/jdk-17.0.12"
export NEO4J_HOME="$install_dir/neo4j-build"
export PATH=$PATH:"$install_dir/java/jdk-17.0.12/bin"
export PATH=$PATH:"$install_dir/maven/apache-maven-3.9.12/bin"
export PATH=$PATH:"$NEO4J_HOME/bin"

alias memgraph="$install_dir/memgraph/usr/lib/memgraph/memgraph"
alias mgconsole="$install_dir/memgraph/usr/bin/mgconsole"
