script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export JAVA_HOME="$script_dir/java/jdk-17.0.12"
export JDK_HOME="$script_dir/java/jdk-17.0.12"
export JRE_HOME="$script_dir/java/jdk-17.0.12"
export NEO4J_HOME="$script_dir/neo4j-build"
export PATH=$PATH:"$script_dir/java/jdk-17.0.12/bin"
export PATH=$PATH:"$script_dir/maven/apache-maven-3.9.12/bin"
export PATH=$PATH:"$NEO4J_HOME/bin"

alias memgraph="$script_dir/memgraph/usr/lib/memgraph/memgraph"
alias mgconsole="$script_dir/memgraph/usr/bin/mgconsole"
